export const GENRES_BOOKS: { label: string; value: string }[] = [
  { label: "Fiction", value: "fiction" },
  { label: "Non-Fiction", value: "non-fiction" },
  { label: "Science Fiction", value: "science-fiction" },
  { label: "Fantasy", value: "fantasy" },
  { label: "Mystery", value: "mystery" },
  { label: "Thriller", value: "thriller" },
  { label: "Horror", value: "horror" },
  { label: "Romance", value: "romance" },
  { label: "Historical Fiction", value: "historical-fiction" },
  { label: "Biography", value: "biography" },
  { label: "Self-Help", value: "self-help" },
  { label: "Science", value: "science" },
  { label: "Philosophy", value: "philosophy" },
  { label: "Poetry", value: "poetry" },
  { label: "Children", value: "children" },
];
