export const GENRES_BOOKS: { label: string; value: string }[] = [
  { label: "Fiction", value: "Fiction" },
  { label: "Non-Fiction", value: "Non-fiction" },
  { label: "Science Fiction", value: "Science Fiction" },
  { label: "Fantasy", value: "Fantasy" },
  { label: "Mystery", value: "Mystery" },
  { label: "Thriller", value: "Thriller" },
  { label: "Horror", value: "Horror" },
  { label: "Romance", value: "Romance" },
  { label: "Historical Fiction", value: "Historical Fiction" },
  { label: "Biography", value: "Biography" },
  { label: "Self-Help", value: "Self-Help" },
  { label: "Science", value: "Science" },
  { label: "Philosophy", value: "Philosophy" },
  { label: "Poetry", value: "Poetry" },
  { label: "Children", value: "Children" },
];
